const KEY='hr_payroll_v2';
const empty={branches:[],departments:[],sections:[],jobs:[],grades:[],categories:[],salaries:[],salaryStructures:[],allowances:[],employees:[],payrolls:[],disbursements:[],experienceAdjustments:[]};
let db=empty; let currentPage='dashboard'; let serverReady=false; let saveTimer=null;
function localFallback(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||empty}catch(e){return empty}}
function save(){localStorage.setItem(KEY,JSON.stringify(db)); clearTimeout(saveTimer); saveTimer=setTimeout(async()=>{if(!serverReady)return; try{const r=await fetch('api.php?action=save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(db)}); if(!r.ok) console.warn('تعذر حفظ البيانات على الخادم'); else setSync('تم الحفظ على الخادم');}catch(e){console.warn(e);setSync('غير متصل - البيانات محفوظة محلياً')}} ,120)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function setSync(t){const x=document.getElementById('syncStatus');if(x)x.textContent=t}
async function boot(){
  try{
    const r=await fetch('api.php?action=state',{credentials:'same-origin'});
    if(r.status===401){showLogin();return}
    const j=await r.json();
    db=j.data&&typeof j.data==='object'?j.data:localFallback();
    serverReady=true;
    if(!j.data || Object.keys(j.data).length===0){const local=localFallback(); if(Object.values(local).some(a=>Array.isArray(a)&&a.length)){db=local;save()}}
    setSync('متصل بالخادم'); render();
  }catch(e){db=localFallback();serverReady=false;setSync('وضع محلي مؤقت');render();}
}
function showLogin(){
  const m=document.getElementById('modal');document.getElementById('modalTitle').textContent='تسجيل الدخول';
  document.getElementById('modalBody').innerHTML='<div class="modal-content"><p class="hint">أدخل بيانات مدير النظام للوصول إلى البيانات المشتركة.</p><div class="field"><label>اسم المستخدم</label><input id="loginUser" value="admin" autocomplete="username"></div><div class="field"><label>كلمة المرور</label><input id="loginPass" type="password" autocomplete="current-password"></div><div class="form-actions"><button class="btn btn-primary" onclick="doLogin()">دخول</button></div><div id="loginErr" class="hint"></div></div>';
  m.classList.remove('hidden');
}
async function doLogin(){const u=document.getElementById('loginUser').value,p=document.getElementById('loginPass').value;const err=document.getElementById('loginErr');try{const r=await fetch('api.php?action=login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({username:u,password:p})});const j=await r.json();if(!r.ok)throw Error(j.message||'بيانات الدخول غير صحيحة');closeModal();await boot()}catch(e){err.textContent=e.message}}

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2})} function toggleSidebar(){sidebar.classList.toggle('open')} function closeModal(){modal.classList.add('hidden')}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();sidebar.classList.remove('open')});
const cfg={branches:['الفروع','اسم الفرع'],departments:['الإدارات','اسم الإدارة'],sections:['الأقسام','اسم القسم'],jobs:['الوظائف','اسم الوظيفة'],grades:['الدرجات الوظيفية','اسم الدرجة'],categories:['الفئات','اسم الفئة'],salaries:['الرواتب الأساسية','قيمة الراتب']};
function nameOf(t,id){let x=db[t].find(a=>a.id===id);return x?(x.name??x.value):'-'} function opts(t,s=''){return '<option value="">اختر</option>'+db[t].map(x=>`<option value="${x.id}" ${x.id===s?'selected':''}>${esc(x.name??x.value)}</option>`).join('')}
function card(t,n){return `<div class="card"><div>${t}</div><div class="num">${fmt(n)}</div></div>`}
function dashboard(){let active=db.employees.filter(e=>e.status!=='stopped').length; app.innerHTML=`<div class="page-head"><div><h2>الرئيسية</h2><div class="hint">دورة الرواتب: موظف ← هيكلة ← بدلات ← خبرة ← مسير ← مصارفة</div></div><span id="syncStatus" class="hint">...</span><button class="btn btn-secondary" onclick="printScreen('لوحة النظام')">🖨 طباعة</button></div><div class="cards">${card('الموظفون',active)}${card('هيكلة الرواتب',db.salaries.length)}${card('البدلات',db.allowances.length)}${card('مسيرات الرواتب',db.payrolls.length)}</div><div class="panel" style="margin-top:16px"><h3>منطق النظام</h3><p>الراتب الأساسي مصدره هيكلة الدرجة والفئة. البدلات تُحسب حسب تعريفها. الخبرة تُحسب من تاريخ التوظيف ويمكن إضافة تعديل معتمد. المسير الشهري يحفظ لقطة مستقلة حتى لا تتغير الرواتب التاريخية عند تعديل بيانات الموظف.</p></div>`}
function setupPage(t){let [title,label]=cfg[t];app.innerHTML=`<div class="page-head"><div><h2>تهيئة ${title}</h2><div class="hint">إضافة وتعديل وحذف وطباعة بيانات ${title}</div></div><div class="toolbar"><button class="btn btn-primary" onclick="addSetup('${t}')">+ إضافة</button><button class="btn btn-secondary" onclick="printScreen('تهيئة ${title}')">🖨 طباعة</button></div></div><div class="table-wrap">${db[t].length?`<table class="table"><tr><th>#</th><th>${label}</th><th>إجراء</th></tr>${db[t].map((x,i)=>`<tr><td>${i+1}</td><td>${fmt(t==='salaries'?x.value:x.name)}</td><td><div class="actions"><button class="btn btn-secondary small" onclick="editSetup('${t}','${x.id}')">تعديل</button><button class="btn btn-danger small" onclick="confirmDelete('السجل',()=>del('${t}','${x.id}'))">حذف</button><button class="btn btn-secondary small" onclick="printRecord('${title}','${esc(t==='salaries'?x.value:x.name)}')">طباعة</button></div></td></tr>`).join('')}</table>`:'<div class="empty">لا توجد بيانات</div>'}</div>`}
function editSetup(t,id){let x=db[t].find(a=>a.id===id),[title,label]=cfg[t];modalTitle.textContent='تعديل '+title;modalBody.innerHTML=`<div class="modal-content"><div class="field"><label>${label}</label><input id="sv" type="${t==='salaries'?'number':'text'}" value="${esc(t==='salaries'?x.value:x.name)}"></div><div class="form-actions"><button class="btn btn-primary" onclick="updateSetup('${t}','${id}')">حفظ التعديل</button><button class="btn btn-secondary" onclick="closeModal()">إلغاء</button></div></div>`;modal.classList.remove('hidden')}
function updateSetup(t,id){let x=db[t].find(a=>a.id===id),v=sv.value.trim();if(!v)return alert('أدخل القيمة');if(t==='salaries')x.value=Number(v);else x.name=v;save();closeModal();render()}
function printRecord(title,value){const w=window.open('','_blank');if(!w)return;w.document.write(`<html lang="ar" dir="rtl"><body style="font-family:Tahoma;padding:40px"><h2>${esc(title)}</h2><p>${value}</p><script>window.print()<\/script></body></html>`);w.document.close()}
function addSetup(t){let [title,label]=cfg[t];modalTitle.textContent='إضافة '+title;modalBody.innerHTML=`<div class="modal-content"><div class="field"><label>${label}</label><input id="sv" type="${t==='salaries'?'number':'text'}"></div><div class="form-actions"><button class="btn btn-primary" onclick="saveSetup('${t}')">حفظ</button></div></div>`;modal.classList.remove('hidden')}
function saveSetup(t){let v=sv.value.trim();if(!v)return alert('أدخل القيمة');db[t].push({id:uid(),...(t==='salaries'?{value:Number(v)}:{name:v})});save();closeModal();render()} function del(t,id){if(confirm('حذف السجل؟')){db[t]=db[t].filter(x=>x.id!==id);save();render()}}
function printScreen(title='النظام'){
 const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Tahoma,Arial;padding:25px;direction:rtl}h1{font-size:20px;border-bottom:2px solid #176b3a;padding-bottom:10px}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #999;padding:7px;text-align:right}th{background:#eee}.no-print{display:none!important}</style></head><body><h1>${esc(title)}</h1>${app.innerHTML}</body></html>`;
 const w=window.open('','_blank'); if(!w)return alert('السماح بالنوافذ المنبثقة مطلوب للطباعة'); w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),300);
}
function confirmDelete(label,fn){if(confirm('هل أنت متأكد من حذف '+label+'؟'))fn()}
function experienceParts(date,ref=new Date()){if(!date)return {y:0,m:0,d:0};let s=new Date(date+'T00:00:00'),e=ref;if(s>e)return {y:0,m:0,d:0};let y=e.getFullYear()-s.getFullYear(),m=e.getMonth()-s.getMonth(),d=e.getDate()-s.getDate();if(d<0){m--;d+=new Date(e.getFullYear(),e.getMonth(),0).getDate()}if(m<0){y--;m+=12}return{y,m,d}}
function expText(p){return `${p.y} سنة ${p.m} شهر ${p.d} يوم`}
function employeePage(){app.innerHTML=`<div class="page-head"><div><h2>بيانات الموظفين</h2><div class="hint">البيانات الأساسية + الخبرة + البدلات</div></div><div class="toolbar"><button class="btn btn-primary" onclick="employeeForm()">+ إضافة</button><button class="btn btn-secondary" onclick="printScreen('بيانات الموظفين')">🖨 طباعة</button></div></div><div class="toolbar"><input class="search" id="eq" placeholder="بحث بالرقم أو الاسم" oninput="employeeRows(this.value)"></div><div class="table-wrap"><table class="table"><thead><tr><th>الرقم</th><th>الموظف</th><th>الإدارة</th><th>القسم</th><th>الوظيفة</th><th>التوظيف</th><th>الخبرة</th><th>الدرجة</th><th>الفئة</th><th>الأساسي</th><th>البدلات</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody id="er"></tbody></table></div>`;employeeRows('')}
function employeeRows(q){let a=db.employees.filter(e=>(e.serial+' '+e.name+' '+nameOf('departments',e.departmentId)+' '+nameOf('sections',e.sectionId)).toLowerCase().includes(String(q||'').toLowerCase()));er.innerHTML=a.length?a.map(e=>`<tr><td>${esc(e.serial)}</td><td><b>${esc(e.name)}</b></td><td>${nameOf('departments',e.departmentId)}</td><td>${nameOf('sections',e.sectionId)}</td><td>${nameOf('jobs',e.jobId)}</td><td>${e.hireDate||'-'}</td><td>${expText(experienceParts(e.hireDate))}</td><td>${nameOf('grades',e.gradeId)}</td><td>${nameOf('categories',e.categoryId)}</td><td>${fmt(e.salary)}</td><td>${fmt(calcAllowances(e).total)}</td><td>${e.status==='stopped'?'غير نشط':'على رأس العمل'}</td><td><button class="btn btn-secondary small" onclick="employeeForm('${e.id}')">تعديل</button> <button class="btn btn-secondary small" onclick="allowanceModal('${e.id}')">البدلات</button> <button class="btn btn-danger small" onclick="confirmDelete('الموظف',()=>delEmp('${e.id}'))">حذف</button> <button class="btn btn-secondary small" onclick="printEmployee('${e.id}')">طباعة</button></td></tr>`).join(''):'<tr><td colspan="13" class="empty">لا توجد بيانات</td></tr>'}
function printEmployee(id){let e=db.employees.find(x=>x.id===id);const w=window.open('','_blank');if(!w)return;w.document.write(`<html lang="ar" dir="rtl"><body style="font-family:Tahoma;padding:30px"><h2>بيانات الموظف</h2><table border="1" cellpadding="8" cellspacing="0"><tr><th>الرقم</th><td>${esc(e.serial)}</td></tr><tr><th>الاسم</th><td>${esc(e.name)}</td></tr><tr><th>الإدارة</th><td>${esc(nameOf('departments',e.departmentId))}</td></tr><tr><th>القسم</th><td>${esc(nameOf('sections',e.sectionId))}</td></tr><tr><th>الوظيفة</th><td>${esc(nameOf('jobs',e.jobId))}</td></tr><tr><th>تاريخ التوظيف</th><td>${e.hireDate||'-'}</td></tr><tr><th>الخبرة</th><td>${expText(experienceParts(e.hireDate))}</td></tr><tr><th>الراتب الأساسي</th><td>${fmt(e.salary)}</td></tr></table><script>window.print()<\/script></body></html>`);w.document.close()}
function employeeForm(id){let e=db.employees.find(x=>x.id===id)||{serial:String(db.employees.length+1).padStart(5,'0')};modalTitle.textContent=id?'تعديل الموظف':'موظف جديد';modalBody.innerHTML=`<div class="modal-content"><div class="form-grid"><div class="field"><label>الرقم التسلسلي</label><input id="es" value="${esc(e.serial)}" readonly></div><div class="field"><label>اسم الموظف</label><input id="en" value="${esc(e.name||'')}"></div><div class="field"><label>الفرع</label><select id="eb">${opts('branches',e.branchId)}</select></div><div class="field"><label>حالة الموظف</label><select id="est"><option value="active" ${e.status==='active'||!e.status?'selected':''}>على رأس العمل</option><option value="stopped" ${e.status==='stopped'?'selected':''}>موقوف/غير نشط</option></select></div><div class="field"><label>الإدارة</label><select id="ed">${opts('departments',e.departmentId)}</select></div><div class="field"><label>القسم</label><select id="ec">${opts('sections',e.sectionId)}</select></div><div class="field"><label>الوظيفة</label><select id="ej">${opts('jobs',e.jobId)}</select></div><div class="field"><label>تاريخ التوظيف</label><input id="eh" type="date" value="${e.hireDate||''}" oninput="ep.textContent=expText(experienceParts(this.value))"></div><div class="field"><label>تاريخ التثبيت</label><input id="ef" type="date" value="${e.fixDate||''}"></div><div class="field"><label>الخبرة الحالية</label><input id="ep" value="${expText(experienceParts(e.hireDate))}" readonly></div><div class="field"><label>الدرجة الوظيفية</label><select id="eg">${opts('grades',e.gradeId)}</select></div><div class="field"><label>الفئة</label><select id="ect">${opts('categories',e.categoryId)}</select></div><div class="field"><label>الراتب الأساسي</label><input id="esal" type="number" value="${e.salary||''}"></div></div><div class="form-actions"><button class="btn btn-primary" onclick="saveEmp('${id||''}')">حفظ</button></div></div>`;modal.classList.remove('hidden')}
function employeeForm(id){let e=db.employees.find(x=>x.id===id)||{serial:String(db.employees.length+1).padStart(5,'0')};modalTitle.textContent=id?'تعديل الموظف':'موظف جديد';modalBody.innerHTML=`<div class="modal-content"><div class="form-grid"><div class="field"><label>الرقم التسلسلي</label><input id="es" value="${esc(e.serial)}" readonly></div><div class="field"><label>اسم الموظف</label><input id="en" value="${esc(e.name||'')}"></div><div class="field"><label>الفرع</label><select id="eb">${opts('branches',e.branchId)}</select></div><div class="field"><label>حالة الموظف</label><select id="est"><option value="active" ${e.status==='active'||!e.status?'selected':''}>على رأس العمل</option><option value="stopped" ${e.status==='stopped'?'selected':''}>موقوف/غير نشط</option></select></div><div class="field"><label>الإدارة</label><select id="ed">${opts('departments',e.departmentId)}</select></div><div class="field"><label>القسم</label><select id="ec">${opts('sections',e.sectionId)}</select></div><div class="field"><label>الوظيفة</label><select id="ej">${opts('jobs',e.jobId)}</select></div><div class="field"><label>تاريخ التوظيف</label><input id="eh" type="date" value="${e.hireDate||''}" oninput="ep.textContent=expText(experienceParts(this.value))"></div><div class="field"><label>تاريخ التثبيت</label><input id="ef" type="date" value="${e.fixDate||''}"></div><div class="field"><label>الخبرة الحالية</label><input id="ep" value="${expText(experienceParts(e.hireDate))}" readonly></div><div class="field"><label>الدرجة الوظيفية</label><select id="eg">${opts('grades',e.gradeId)}</select></div><div class="field"><label>الفئة</label><select id="ect">${opts('categories',e.categoryId)}</select></div><div class="field"><label>الراتب الأساسي</label><input id="esal" type="number" value="${e.salary||''}"></div></div><div class="form-actions"><button class="btn btn-primary" onclick="saveEmp('${id||''}')">حفظ</button></div></div>`;modal.classList.remove('hidden')}
function saveEmp(id){if(!en.value.trim())return alert('اسم الموظف مطلوب');let o={id:id||uid(),serial:es.value,name:en.value.trim(),branchId:eb.value,departmentId:ed.value,sectionId:ec.value,jobId:ej.value,hireDate:eh.value,fixDate:ef.value,gradeId:eg.value,categoryId:ect.value,salary:Number(esal.value||0),status:est.value};if(id)db.employees[db.employees.findIndex(x=>x.id===id)]=o;else db.employees.push(o);save();closeModal();render()}function delEmp(id){if(confirm('حذف الموظف؟')){db.employees=db.employees.filter(x=>x.id!==id);save();render()}}
function allowanceModal(id){let e=db.employees.find(x=>x.id===id);modalTitle.textContent='بدلات: '+e.name;modalBody.innerHTML=`<div class="modal-content"><div class="toolbar"><button class="btn btn-primary" onclick="addAllowance()">تهيئة بدل</button><button class="btn btn-secondary" onclick="assignAllowance('${id}')">إضافة بدل للموظف</button></div>${allowanceTable(e)}</div>`;modal.classList.remove('hidden')}
function allowanceTable(e){let a=db.allowances.filter(x=>(x.employeeIds||[]).includes(e.id));return `<table class="table"><tr><th>البدل</th><th>التصنيف</th><th>النوع</th><th>القيمة</th><th>المحتسب</th></tr>${a.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.kind}</td><td>${x.type==='percentage'?'نسبة':'ثابت'}</td><td>${x.value}${x.type==='percentage'?'%':''}</td><td>${fmt(x.type==='percentage'?e.salary*x.value/100:x.value)}</td></tr>`).join('')}</table><div class="allowance-total">إجمالي البدلات: ${fmt(calcAllowances(e).total)}</div>`}
function addAllowance(){modalTitle.textContent='تهيئة بدل';modalBody.innerHTML=`<div class="modal-content"><div class="form-grid"><div class="field"><label>اسم البدل</label><input id="an"></div><div class="field"><label>التصنيف</label><select id="ak"><option value="official">رسمي</option><option value="administrative">إداري</option><option value="conditional">مشروط</option></select></div><div class="field"><label>النوع</label><select id="at"><option value="fixed">ثابت</option><option value="percentage">نسبة من الأساسي</option></select></div><div class="field"><label>القيمة</label><input id="av" type="number"></div><div class="field"><label>شرط الاستحقاق/ملاحظة</label><input id="ac"></div></div><div class="form-actions"><button class="btn btn-primary" onclick="saveAllowance()">حفظ</button></div></div>`;modal.classList.remove('hidden')}
function saveAllowance(){if(!an.value.trim())return alert('اسم البدل مطلوب');db.allowances.push({id:uid(),name:an.value.trim(),kind:ak.value,type:at.value,value:Number(av.value||0),condition:ac.value,employeeIds:[]});save();closeModal();render()}
function assignAllowance(eid){let av=db.allowances.filter(a=>!(a.employeeIds||[]).includes(eid));modalTitle.textContent='إضافة بدل للموظف';modalBody.innerHTML='<div class="modal-content">'+(av.length?av.map(a=>`<div class="card" style="margin-bottom:8px;display:flex;justify-content:space-between"><span>${esc(a.name)} — ${a.type==='percentage'?a.value+'%':'ثابت '+fmt(a.value)}</span><button class="btn btn-primary small" onclick="attach('${a.id}','${eid}')">إضافة</button></div>`).join(''):'<div class="empty">لا توجد بدلات متاحة</div>')+'</div>'}
function attach(aid,eid){let a=db.allowances.find(x=>x.id===aid);a.employeeIds=a.employeeIds||[];a.employeeIds.push(eid);save();allowanceModal(eid)}
function calcAllowances(e){let total=0,official=0,administrative=0,conditional=0;db.allowances.filter(a=>(a.employeeIds||[]).includes(e.id)).forEach(a=>{let v=a.type==='percentage'?e.salary*a.value/100:a.value;total+=v;if(a.kind==='official')official+=v;else if(a.kind==='administrative')administrative+=v;else conditional+=v});return{total,official,administrative,conditional}}
function salaryStructure(){app.innerHTML=`<div class="page-head"><div><h2>هيكلة الرواتب</h2><div class="hint">تعريف الأساسي والبدلات القياسية حسب الدرجة والفئة</div></div><div class="toolbar"><button class="btn btn-primary" onclick="structureForm()">+ إضافة</button><button class="btn btn-secondary" onclick="printScreen('هيكلة الرواتب')">🖨 طباعة</button></div></div><div class="table-wrap"><table class="table"><tr><th>الدرجة</th><th>الفئة</th><th>المسمى</th><th>المستوى</th><th>الأساسي</th><th>طبيعة العمل</th><th>المظهر</th><th>العلاج</th><th>التأمينات</th><th>إجراء</th></tr>${(db.salaryStructures||[]).map(s=>`<tr><td>${esc(s.grade)}</td><td>${esc(s.category)}</td><td>${esc(s.title||'')}</td><td>${esc(s.level||'')}</td><td>${fmt(s.basic)}</td><td>${s.workPct}%</td><td>${s.appearancePct}%</td><td>${s.medicalPct}%</td><td>${s.insurancePct}%</td><td><button class="btn btn-secondary small" onclick="editStructure('${s.id}')">تعديل</button><button class="btn btn-danger small" onclick="confirmDelete('هيكلة الراتب',()=>{db.salaryStructures=db.salaryStructures.filter(x=>x.id!=='${s.id}');save();render()})">حذف</button><button class="btn btn-secondary small" onclick="printRecord('هيكلة الراتب','${esc(s.grade)} — ${esc(s.category)} — ${fmt(s.basic)}')">طباعة</button></td></tr>`).join('')}</table></div>`}
function editStructure(id){let s=db.salaryStructures.find(x=>x.id===id);modalTitle.textContent='تعديل هيكلة راتب';modalBody.innerHTML=`<div class="modal-content"><div class="form-grid"><div class="field"><label>الدرجة</label><input id="sg" value="${esc(s.grade)}"></div><div class="field"><label>الفئة</label><input id="sct" value="${esc(s.category)}"></div><div class="field"><label>المسمى</label><input id="st" value="${esc(s.title||'')}"></div><div class="field"><label>المستوى</label><input id="sl" value="${esc(s.level||'')}"></div><div class="field"><label>الأساسي</label><input id="sb" type="number" value="${s.basic}"></div><div class="field"><label>طبيعة العمل %</label><input id="sw" type="number" value="${s.workPct}"></div><div class="field"><label>المظهر %</label><input id="sa" type="number" value="${s.appearancePct}"></div><div class="field"><label>العلاج %</label><input id="sm" type="number" value="${s.medicalPct}"></div><div class="field"><label>التأمينات %</label><input id="si" type="number" value="${s.insurancePct}"></div></div><div class="form-actions"><button class="btn btn-primary" onclick="updateStructure('${id}')">حفظ التعديل</button></div></div>`;modal.classList.remove('hidden')}
function updateStructure(id){let s=db.salaryStructures.find(x=>x.id===id);s.grade=sg.value;s.category=sct.value;s.title=st.value;s.level=sl.value;s.basic=Number(sb.value||0);s.workPct=Number(sw.value||0);s.appearancePct=Number(sa.value||0);s.medicalPct=Number(sm.value||0);s.insurancePct=Number(si.value||0);save();closeModal();render()}
function structureForm(){modalTitle.textContent='إضافة هيكلة راتب';modalBody.innerHTML=`<div class="modal-content"><div class="form-grid"><div class="field"><label>الدرجة</label><input id="sg"></div><div class="field"><label>الفئة</label><input id="sct"></div><div class="field"><label>المسمى الوظيفي</label><input id="st"></div><div class="field"><label>المستوى</label><input id="sl"></div><div class="field"><label>الراتب الأساسي</label><input id="sb" type="number"></div><div class="field"><label>طبيعة العمل %</label><input id="sw" type="number" value="52"></div><div class="field"><label>المظهر %</label><input id="sa" type="number" value="17.5"></div><div class="field"><label>العلاج %</label><input id="sm" type="number" value="17"></div><div class="field"><label>التأمينات %</label><input id="si" type="number" value="18"></div></div><div class="form-actions"><button class="btn btn-primary" onclick="saveStructure()">حفظ</button></div></div>`;modal.classList.remove('hidden')}
function saveStructure(){db.salaryStructures=db.salaryStructures||[];db.salaryStructures.push({id:uid(),grade:sg.value,category:sct.value,title:st.value,level:sl.value,basic:Number(sb.value||0),workPct:Number(sw.value||0),appearancePct:Number(sa.value||0),medicalPct:Number(sm.value||0),insurancePct:Number(si.value||0)});save();closeModal();render()}
function payroll(){
 const rows=db.payrolls.slice().reverse();
 app.innerHTML=`<div class="page-head"><div><h2>مسيرات الرواتب الشهرية</h2><div class="hint">كل مسير محفوظ مستقلًا ويمكن تعديله أو حذفه أو طباعته</div></div><div class="toolbar"><button class="btn btn-primary" onclick="createPayroll()">+ إضافة مسير</button><button class="btn btn-secondary" onclick="printScreen('مسيرات الرواتب')">🖨 طباعة</button></div></div><div class="table-wrap"><table class="table"><tr><th>#</th><th>الشهر</th><th>الموظفون</th><th>الإجمالي</th><th>تاريخ الإنشاء</th><th>إجراء</th></tr>${rows.length?rows.map((p,i)=>`<tr><td>${rows.length-i}</td><td><b>${esc(p.month)}</b></td><td>${p.rows.length}</td><td>${fmt(p.total)}</td><td>${(p.createdAt||'').slice(0,10)}</td><td><div class="actions"><button class="btn btn-secondary small" onclick="viewPayroll('${p.id}')">عرض</button><button class="btn btn-secondary small" onclick="editPayroll('${p.id}')">تعديل</button><button class="btn btn-danger small" onclick="confirmDelete('المسير',()=>deletePayroll('${p.id}'))">حذف</button><button class="btn btn-secondary small" onclick="printPayroll('${p.id}')">طباعة</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty">لم يتم إنشاء أي مسير بعد.</td></tr>'}</table></div><div id="payrollView"></div>`;
}
function createPayroll(){let month=prompt('أدخل شهر المسير بصيغة YYYY-MM',new Date().toISOString().slice(0,7));if(!month)return;if(db.payrolls.some(p=>p.month===month))return alert('يوجد مسير محفوظ لهذا الشهر بالفعل');let rows=db.employees.filter(e=>e.status!=='stopped').map(e=>{let a=calcAllowances(e);let gross=Number(e.salary||0)+a.total;let deduction=0;return{employeeId:e.id,serial:e.serial,name:e.name,basic:Number(e.salary||0),official:a.official,administrative:a.administrative,conditional:a.conditional,gross,deduction,net:gross-deduction}});db.payrolls.push({id:uid(),month,createdAt:new Date().toISOString(),rows,total:rows.reduce((x,r)=>x+r.net,0)});save();render()}
function viewPayroll(id){let p=db.payrolls.find(x=>x.id===id);if(!p)return;payrollView.innerHTML=`<div class="panel" style="margin-top:12px"><div class="page-head"><div><h3>تفاصيل مسير ${esc(p.month)}</h3><div class="hint">${p.rows.length} موظف — إجمالي ${fmt(p.total)}</div></div><button class="btn btn-secondary" onclick="printPayroll('${p.id}')">🖨 طباعة المسير</button></div><div class="table-wrap"><table class="table"><tr><th>الرقم</th><th>الموظف</th><th>الأساسي</th><th>رسمي</th><th>إداري</th><th>مشروط</th><th>الإجمالي</th><th>خصم</th><th>الصافي</th></tr>${p.rows.map(r=>`<tr><td>${esc(r.serial)}</td><td>${esc(r.name)}</td><td>${fmt(r.basic)}</td><td>${fmt(r.official)}</td><td>${fmt(r.administrative)}</td><td>${fmt(r.conditional)}</td><td>${fmt(r.gross)}</td><td>${fmt(r.deduction)}</td><td><b>${fmt(r.net)}</b></td></tr>`).join('')}</table></div></div>`}
function editPayroll(id){let p=db.payrolls.find(x=>x.id===id);if(!p)return;let m=prompt('تعديل شهر المسير',p.month);if(m===null||!m.trim())return;if(m!==p.month&&db.payrolls.some(x=>x.id!==id&&x.month===m.trim()))return alert('يوجد مسير آخر لهذا الشهر');p.month=m.trim();save();render()}
function deletePayroll(id){db.payrolls=db.payrolls.filter(x=>x.id!==id);db.disbursements=db.disbursements.filter(x=>x.payrollId!==id);save();render()}
function printPayroll(id){let p=db.payrolls.find(x=>x.id===id);if(!p)return;const html=`<h1>مسير الرواتب - ${esc(p.month)}</h1><p>عدد الموظفين: ${p.rows.length} — الإجمالي: ${fmt(p.total)}</p><table><tr><th>الرقم</th><th>الموظف</th><th>الأساسي</th><th>رسمي</th><th>إداري</th><th>مشروط</th><th>الصافي</th></tr>${p.rows.map(r=>`<tr><td>${esc(r.serial)}</td><td>${esc(r.name)}</td><td>${fmt(r.basic)}</td><td>${fmt(r.official)}</td><td>${fmt(r.administrative)}</td><td>${fmt(r.conditional)}</td><td>${fmt(r.net)}</td></tr>`).join('')}</table>`;printHtml('مسير الرواتب',html)}
function printHtml(title,body){const w=window.open('','_blank');if(!w)return alert('السماح بالنوافذ المنبثقة مطلوب للطباعة');w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Tahoma,Arial;padding:25px;direction:rtl}h1{font-size:20px;border-bottom:2px solid #176b3a;padding-bottom:10px}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #999;padding:7px;text-align:right}th{background:#eee}</style></head><body>${body}<script>window.print()<\/script></body></html>`);w.document.close()}
function experience(){let ref=new Date();app.innerHTML=`<div class="page-head"><div><h2>كشف الخبرة</h2><div class="hint">الخبرة المحسوبة والتعديلات المعتمدة لكل موظف</div></div><div class="toolbar"><button class="btn btn-secondary" onclick="printScreen('كشف الخبرة')">🖨 طباعة</button></div></div><div class="table-wrap"><table class="table"><tr><th>الرقم</th><th>الموظف</th><th>التوظيف</th><th>أيام</th><th>أشهر</th><th>سنوات</th><th>إضافة معتمدة</th><th>السنوات الفعلية</th><th>إجراء</th></tr>${db.employees.map(e=>{let p=experienceParts(e.hireDate,ref);let adj=db.experienceAdjustments.filter(x=>x.employeeId===e.id).reduce((a,x)=>a+Number(x.years||0),0);return `<tr><td>${e.serial}</td><td>${esc(e.name)}</td><td>${e.hireDate||'-'}</td><td>${p.d}</td><td>${p.m}</td><td>${p.y}</td><td>${adj}</td><td>${p.y+adj}</td><td><button class="btn btn-secondary small" onclick="editExperience('${e.id}')">تعديل</button><button class="btn btn-secondary small" onclick="printExperience('${e.id}')">طباعة</button></td></tr>`}).join('')}</table></div>`}
function editExperience(id){let e=db.employees.find(x=>x.id===id);if(!e)return;let old=db.experienceAdjustments.filter(x=>x.employeeId===e.id).reduce((a,x)=>a+Number(x.years||0),0);let years=prompt('سنوات الخبرة الإضافية المعتمدة',old);if(years===null)return;db.experienceAdjustments=db.experienceAdjustments.filter(x=>x.employeeId!==e.id);if(Number(years))db.experienceAdjustments.push({id:uid(),employeeId:e.id,years:Number(years),note:'تعديل إداري'});save();render()}
function printExperience(id){let e=db.employees.find(x=>x.id===id);if(!e)return;let p=experienceParts(e.hireDate),adj=db.experienceAdjustments.filter(x=>x.employeeId===id).reduce((a,x)=>a+Number(x.years||0),0);printHtml('كشف خبرة موظف',`<h1>كشف خبرة موظف</h1><p><b>الاسم:</b> ${esc(e.name)} &nbsp; <b>الرقم:</b> ${esc(e.serial)}</p><table><tr><th>تاريخ التوظيف</th><th>الأيام</th><th>الأشهر</th><th>السنوات</th><th>إضافة معتمدة</th><th>السنوات الفعلية</th></tr><tr><td>${e.hireDate||'-'}</td><td>${p.d}</td><td>${p.m}</td><td>${p.y}</td><td>${adj}</td><td>${p.y+adj}</td></tr></table>`)}
function employeeSlip(){app.innerHTML=`<div class="page-head"><h2>كشف راتب موظف</h2><div class="toolbar"><select id="selEmp" class="search" onchange="showSlip(this.value)"><option value="">اختر الموظف</option>${db.employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select><button class="btn btn-secondary" onclick="editSelectedEmployee()">تعديل</button><button class="btn btn-danger" onclick="deleteSelectedEmployee()">حذف</button><button class="btn btn-secondary" onclick="printScreen('كشف راتب موظف')">🖨 طباعة</button></div></div><div id="slip"></div>`}
function editSelectedEmployee(){if(selEmp.value)employeeForm(selEmp.value);else alert('اختر موظفًا أولاً')} function deleteSelectedEmployee(){if(!selEmp.value)return alert('اختر موظفًا أولاً');confirmDelete('الموظف',()=>delEmp(selEmp.value))}
function showSlip(id){let e=db.employees.find(x=>x.id===id);if(!e)return slip.innerHTML='';let a=calcAllowances(e), p=experienceParts(e.hireDate);slip.innerHTML=`<div class="panel"><h3>بيانات الموظف</h3><div class="grid"><div><b>الاسم:</b> ${esc(e.name)}</div><div><b>الرقم:</b> ${e.serial}</div><div><b>الدرجة:</b> ${nameOf('grades',e.gradeId)}</div><div><b>الفئة:</b> ${nameOf('categories',e.categoryId)}</div><div><b>تاريخ التوظيف:</b> ${e.hireDate||'-'}</div><div><b>الخبرة:</b> ${expText(p)}</div></div><h3>الاستحقاقات</h3><table class="table"><tr><th>البند</th><th>القيمة</th></tr><tr><td>الراتب الأساسي</td><td>${fmt(e.salary)}</td></tr><tr><td>البدلات الرسمية</td><td>${fmt(a.official)}</td></tr><tr><td>البدلات الإدارية</td><td>${fmt(a.administrative)}</td></tr><tr><td>البدلات المشروطة</td><td>${fmt(a.conditional)}</td></tr><tr><th>الإجمالي</th><th>${fmt(e.salary+a.total)}</th></tr></table></div>`}
function disbursement(){let list=db.disbursements.slice().reverse();app.innerHTML=`<div class="page-head"><div><h2>مصارفة الرواتب</h2><div class="hint">سجل مستقل لكل مصارفة مرتبطة بمسير محدد</div></div><div class="toolbar"><button class="btn btn-primary" onclick="newDisbursement()">+ إضافة مصارفة</button><button class="btn btn-secondary" onclick="printScreen('مصارفة الرواتب')">🖨 طباعة</button></div></div><div class="table-wrap"><table class="table"><tr><th>#</th><th>المسير</th><th>سعر التحويل</th><th>التاريخ</th><th>الحالة</th><th>إجراء</th></tr>${list.length?list.map((d,i)=>{let p=db.payrolls.find(x=>x.id===d.payrollId);return `<tr><td>${list.length-i}</td><td>${p?esc(p.month):'-'}</td><td>${fmt(d.rate)}</td><td>${d.date||'-'}</td><td>${esc(d.status||'-')}</td><td><button class="btn btn-secondary small" onclick="editDisbursement('${d.id}')">تعديل</button><button class="btn btn-danger small" onclick="confirmDelete('المصارفة',()=>deleteDisbursement('${d.id}'))">حذف</button><button class="btn btn-secondary small" onclick="printDisbursement('${d.id}')">طباعة</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">لا توجد مصارفات.</td></tr>'}</table></div>`}
function newDisbursement(){if(!db.payrolls.length)return alert('أنشئ مسيرًا أولًا');let optsList=db.payrolls.map(p=>`${p.month}`).join('\n');let month=prompt('أدخل شهر المسير المراد مصارفته:\n'+optsList,db.payrolls[db.payrolls.length-1].month);if(!month)return;let p=db.payrolls.find(x=>x.month===month.trim());if(!p)return alert('المسير غير موجود');let rate=prompt('سعر التحويل','425');if(rate===null)return;let date=prompt('تاريخ المصارفة',new Date().toISOString().slice(0,10));if(!date)return;let status=prompt('حالة المصارفة','مسودة')||'مسودة';db.disbursements.push({id:uid(),payrollId:p.id,rate:Number(rate||0),date,status});save();render()}
function editDisbursement(id){let d=db.disbursements.find(x=>x.id===id);if(!d)return;let r=prompt('سعر التحويل',d.rate);if(r===null)return;d.rate=Number(r||0);d.date=prompt('تاريخ المصارفة',d.date)||d.date;d.status=prompt('حالة المصارفة',d.status)||d.status;save();render()}
function deleteDisbursement(id){db.disbursements=db.disbursements.filter(x=>x.id!==id);save();render()}
function printDisbursement(id){let d=db.disbursements.find(x=>x.id===id);if(!d)return;let p=db.payrolls.find(x=>x.id===d.payrollId);if(!p)return;printHtml('مصارفة الرواتب',`<h1>مصارفة الرواتب - ${esc(p.month)}</h1><p><b>سعر التحويل:</b> ${fmt(d.rate)} — <b>التاريخ:</b> ${esc(d.date)} — <b>الحالة:</b> ${esc(d.status)}</p><table><tr><th>الموظف</th><th>الصافي</th><th>بالتحويل</th></tr>${p.rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${fmt(r.net)}</td><td>${fmt(d.rate?r.net/d.rate:0)}</td></tr>`).join('')}</table>`)}
function editAllowance(id){let a=db.allowances.find(x=>x.id===id);modalTitle.textContent='تعديل بدل';modalBody.innerHTML=`<div class="modal-content"><div class="form-grid"><div class="field"><label>اسم البدل</label><input id="an" value="${esc(a.name)}"></div><div class="field"><label>التصنيف</label><select id="ak"><option value="official" ${a.kind==='official'?'selected':''}>رسمي</option><option value="administrative" ${a.kind==='administrative'?'selected':''}>إداري</option><option value="conditional" ${a.kind==='conditional'?'selected':''}>مشروط</option></select></div><div class="field"><label>النوع</label><select id="at"><option value="fixed" ${a.type==='fixed'?'selected':''}>ثابت</option><option value="percentage" ${a.type==='percentage'?'selected':''}>نسبة من الأساسي</option></select></div><div class="field"><label>القيمة</label><input id="av" type="number" value="${a.value}"></div><div class="field"><label>الشرط</label><input id="ac" value="${esc(a.condition||'')}"></div></div><div class="form-actions"><button class="btn btn-primary" onclick="updateAllowance('${id}')">حفظ التعديل</button></div></div>`;modal.classList.remove('hidden')}
function updateAllowance(id){let a=db.allowances.find(x=>x.id===id);a.name=an.value.trim();a.kind=ak.value;a.type=at.value;a.value=Number(av.value||0);a.condition=ac.value;save();closeModal();render()}
function allowancesPage(){app.innerHTML=`<div class="page-head"><h2>تهيئة البدلات</h2><div class="toolbar"><button class="btn btn-primary" onclick="addAllowance()">+ إضافة</button><button class="btn btn-secondary" onclick="printScreen('تهيئة البدلات')">🖨 طباعة</button></div></div><div class="table-wrap"><table class="table"><tr><th>البدل</th><th>التصنيف</th><th>النوع</th><th>القيمة</th><th>الشرط</th><th>إجراء</th></tr>${db.allowances.map(a=>`<tr><td>${esc(a.name)}</td><td>${a.kind}</td><td>${a.type==='percentage'?'نسبة من الأساسي':'ثابت'}</td><td>${a.value}${a.type==='percentage'?'%':''}</td><td>${esc(a.condition||'-')}</td><td><button class="btn btn-secondary small" onclick="editAllowance('${a.id}')">تعديل</button><button class="btn btn-danger small" onclick="confirmDelete('البدل',()=>del('allowances','${a.id}'))">حذف</button><button class="btn btn-secondary small" onclick="printRecord('البدل','${esc(a.name)} — ${a.value}${a.type==='percentage'?'%':''}')">طباعة</button></td></tr>`).join('')}</table></div>`}
function render(){if(currentPage==='dashboard')dashboard();else if(currentPage==='employees')employeePage();else if(currentPage==='salaryStructure')salaryStructure();else if(currentPage==='payroll')payroll();else if(currentPage==='experience')experience();else if(currentPage==='employeeSlip')employeeSlip();else if(currentPage==='disbursement')disbursement();else if(currentPage==='allowances')allowancesPage();else if(cfg[currentPage])setupPage(currentPage)}
boot();
